server:
  port: 8094
spring:
  application:
    name: account-ntt
  profiles:
    active: dev

  data:
    mongodb:
      uri: mongodb+srv://navlag:Fg3UgAroDl8SDVDt@avsavivd.lfqko.mongodb.net/pmactoob?retryWrites=true&w=majority
